strictness: veryhigh
doc-warnings: true
member-warnings: false
test-warnings: false

ignore-patterns:
  - (^|/)\..+
  - .*\.html
  - docs/.*
  - tmp\.py

pylint:
  options:
    max-args: 10
    max-locals: 100
    max-returns: 10
    max-branches: 50
    max-statements: 180
    max-parents: 10
    max-attributes: 22
    min-public-methods: 0
    max-public-methods: 20
    max-module-lines: 2000
    max-line-length: 100

mccabe:
  options:
    max-complexity: 30

pycodestyle:
  disable:
    - N802
    - N807
    - N818
    - W503
  options:
    max-line-length: 100
    single-line-if-stmt: n

vulture:
  run: false

bandit:
  run: true

pyroma:
  run: false

pydocstyle:
  disable:
    - D000
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D107
    - D200
    - D202
    - D203
    - D205
    - D212
    - D204
    - D300
    - D400
    - D401
    - D404
    - D403
    - D415
