---
name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: build and publish
        run: poetry publish --build -n -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v25
      - run: nix run -f . scripts.docs
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/html'
      - id: deployment
        uses: actions/deploy-pages@v4
