---
name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: build and publish
        run: poetry publish --build -n -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
  docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: cachix/install-nix-action@v27
      - run: nix run -f . scripts.docs
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: 'docs/build/html'
      - id: deployment
        uses: actions/deploy-pages@v4.0.5
